  version: '3.9'

  services:
    postgres:
      image: postgres:15.10-alpine3.20
      container_name: postgres
      #ports:
       # - '5432:5432'
      volumes:
        - fastapi_pg:/var/lib/postgresql/fastapi_data
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: fastapi
      restart: on-failure

    api:
      container_name: fastapi_app
      depends_on:
        - postgres
      build:
        context: .
      command: >
        sh -c "python3 criar_tabelas.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      ports:
        - 8000:8000
      restart: on-failure

  volumes:
    fastapi_pg: