version: '3.9'

services:
  postgres:
    image: postgres:15.10-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always

  api:
    build:
      context: .
    ports:
      - 5000:5000
    restart: always
